# Generated by Django 4.2 on 2023-12-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
