# Generated by Django 4.2 on 2023-12-15 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CardManager', '0002_projects_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardManager.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardManager.members')),
            ],
        ),
    ]
